name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy React to GitHub Pages
        uses: bitovi/github-actions-react-to-github-pages@v1.2.4
        with:
          path: build
          install_command: npm install
          build_command: npm run build
          caching: true